
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import MySessionProvider from "@/providers/MySessionProvider";
import { ThemeProvider } from "@/providers/ThemeProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { CheckCircle2, AlertCircle } from "lucide-react";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>

      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <MySessionProvider>
            <Toaster
              position="top-center"
              expand={false}
              richColors
              theme="system"
              icons={{
                success: <CheckCircle2 className="w-5 h-5 text-emerald-400" />,
                error: <AlertCircle className="w-5 h-5 text-rose-400" />,
              }}
              toastOptions={{
                style: {
                  borderRadius: '24px',
                  border: '1px solid rgba(255, 255, 255, 0.1)',
                  background: 'rgba(15, 23, 42, 0.95)',
                  backdropFilter: 'blur(20px)',
                  color: '#fff',
                  fontFamily: 'inherit',
                  fontWeight: '900',
                  textTransform: 'uppercase',
                  letterSpacing: '0.15em',
                  fontSize: '10px',
                  boxShadow: '0 25px 50px -12px rgba(0, 0, 0, 0.5)',
                  padding: '16px 24px',
                },
              }}
            />
            <Navbar />
            {children}
            <Footer />
          </MySessionProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
